from machine import Pin
from utime import sleep
led = Pin(13,Pin.OUT)
led1 = Pin(12,Pin.OUT)
led2 = Pin(14,Pin.OUT)
led3 = Pin(27,Pin.OUT)
led4 = Pin(26,Pin.OUT)
led5 = Pin(25,Pin.OUT)
led6 = Pin(15,Pin.OUT)
led7 = Pin(2,Pin.OUT)
led8 = Pin(4,Pin.OUT)
led9 = Pin(2,Pin.OUT)
led10 = Pin(5,Pin.OUT)

pausa = 2

led.value(1)
sleep(pausa)
led.value(0)
led1.value(1)
sleep(pausa)
led1.value(0)
led2.value(1)
sleep(pausa)
led2.value(0)
led3.value(1)
sleep(pausa)
led3.value(0)
led4.value(1)
sleep(pausa)
led4.value(0)
led5.value(1)
sleep(pausa)
led5.value(0)
led6.value(1)
sleep(pausa)
led6.value(0)
led7.value(1)
sleep(pausa)
led7.value(0)
led8.value(1)
sleep(pausa)
led8.value(0)
led9.value(1)
sleep(pausa)
led9.value(0)
led10.value(1)
sleep(pausa)
led10.value(0)
sleep(pausa)